version: '3.8'

services:
  database:
    build: .
    container_name: rcs_database
    env_file:
      - .env
    ports:
      - "5500:5432"
    volumes:
      - ./current_dump.sql:/docker-entrypoint-initdb.d/current_dump.sql